/*
 * This file is generated by jOOQ.
 */
package kr.co.ihab.speechear.persistence.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Function3_1 implements Serializable {

    private static final long serialVersionUID = 1L;

    private String speechcode;
    private String questioncode;
    private String questioncontext;
    private String answer;

    public Function3_1() {}

    public Function3_1(Function3_1 value) {
        this.speechcode = value.speechcode;
        this.questioncode = value.questioncode;
        this.questioncontext = value.questioncontext;
        this.answer = value.answer;
    }

    public Function3_1(
        String speechcode,
        String questioncode,
        String questioncontext,
        String answer
    ) {
        this.speechcode = speechcode;
        this.questioncode = questioncode;
        this.questioncontext = questioncontext;
        this.answer = answer;
    }

    /**
     * Getter for <code>public.function3_1.speechcode</code>.
     */
    public String getSpeechcode() {
        return this.speechcode;
    }

    /**
     * Setter for <code>public.function3_1.speechcode</code>.
     */
    public Function3_1 setSpeechcode(String speechcode) {
        this.speechcode = speechcode;
        return this;
    }

    /**
     * Getter for <code>public.function3_1.questioncode</code>.
     */
    public String getQuestioncode() {
        return this.questioncode;
    }

    /**
     * Setter for <code>public.function3_1.questioncode</code>.
     */
    public Function3_1 setQuestioncode(String questioncode) {
        this.questioncode = questioncode;
        return this;
    }

    /**
     * Getter for <code>public.function3_1.questioncontext</code>.
     */
    public String getQuestioncontext() {
        return this.questioncontext;
    }

    /**
     * Setter for <code>public.function3_1.questioncontext</code>.
     */
    public Function3_1 setQuestioncontext(String questioncontext) {
        this.questioncontext = questioncontext;
        return this;
    }

    /**
     * Getter for <code>public.function3_1.answer</code>.
     */
    public String getAnswer() {
        return this.answer;
    }

    /**
     * Setter for <code>public.function3_1.answer</code>.
     */
    public Function3_1 setAnswer(String answer) {
        this.answer = answer;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Function3_1 other = (Function3_1) obj;
        if (this.speechcode == null) {
            if (other.speechcode != null)
                return false;
        }
        else if (!this.speechcode.equals(other.speechcode))
            return false;
        if (this.questioncode == null) {
            if (other.questioncode != null)
                return false;
        }
        else if (!this.questioncode.equals(other.questioncode))
            return false;
        if (this.questioncontext == null) {
            if (other.questioncontext != null)
                return false;
        }
        else if (!this.questioncontext.equals(other.questioncontext))
            return false;
        if (this.answer == null) {
            if (other.answer != null)
                return false;
        }
        else if (!this.answer.equals(other.answer))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.speechcode == null) ? 0 : this.speechcode.hashCode());
        result = prime * result + ((this.questioncode == null) ? 0 : this.questioncode.hashCode());
        result = prime * result + ((this.questioncontext == null) ? 0 : this.questioncontext.hashCode());
        result = prime * result + ((this.answer == null) ? 0 : this.answer.hashCode());
        return result;
    }
}
