/*
 * This file is generated by jOOQ.
 */
package kr.co.ihab.speechear.persistence.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Function1 implements Serializable {

    private static final long serialVersionUID = 1L;

    private String index;
    private String filename;
    private String context;

    public Function1() {}

    public Function1(Function1 value) {
        this.index = value.index;
        this.filename = value.filename;
        this.context = value.context;
    }

    public Function1(
        String index,
        String filename,
        String context
    ) {
        this.index = index;
        this.filename = filename;
        this.context = context;
    }

    /**
     * Getter for <code>public.function1.index</code>.
     */
    public String getIndex() {
        return this.index;
    }

    /**
     * Setter for <code>public.function1.index</code>.
     */
    public Function1 setIndex(String index) {
        this.index = index;
        return this;
    }

    /**
     * Getter for <code>public.function1.filename</code>.
     */
    public String getFilename() {
        return this.filename;
    }

    /**
     * Setter for <code>public.function1.filename</code>.
     */
    public Function1 setFilename(String filename) {
        this.filename = filename;
        return this;
    }

    /**
     * Getter for <code>public.function1.context</code>.
     */
    public String getContext() {
        return this.context;
    }

    /**
     * Setter for <code>public.function1.context</code>.
     */
    public Function1 setContext(String context) {
        this.context = context;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Function1 other = (Function1) obj;
        if (this.index == null) {
            if (other.index != null)
                return false;
        }
        else if (!this.index.equals(other.index))
            return false;
        if (this.filename == null) {
            if (other.filename != null)
                return false;
        }
        else if (!this.filename.equals(other.filename))
            return false;
        if (this.context == null) {
            if (other.context != null)
                return false;
        }
        else if (!this.context.equals(other.context))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.index == null) ? 0 : this.index.hashCode());
        result = prime * result + ((this.filename == null) ? 0 : this.filename.hashCode());
        result = prime * result + ((this.context == null) ? 0 : this.context.hashCode());
        return result;
    }
}
