/*
 * This file is generated by jOOQ.
 */
package kr.co.ihab.speechear.persistence.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Function3_2 implements Serializable {

    private static final long serialVersionUID = 1L;

    private String speechcode;
    private String speechcontext;

    public Function3_2() {}

    public Function3_2(Function3_2 value) {
        this.speechcode = value.speechcode;
        this.speechcontext = value.speechcontext;
    }

    public Function3_2(
        String speechcode,
        String speechcontext
    ) {
        this.speechcode = speechcode;
        this.speechcontext = speechcontext;
    }

    /**
     * Getter for <code>public.function3_2.speechcode</code>.
     */
    public String getSpeechcode() {
        return this.speechcode;
    }

    /**
     * Setter for <code>public.function3_2.speechcode</code>.
     */
    public Function3_2 setSpeechcode(String speechcode) {
        this.speechcode = speechcode;
        return this;
    }

    /**
     * Getter for <code>public.function3_2.speechcontext</code>.
     */
    public String getSpeechcontext() {
        return this.speechcontext;
    }

    /**
     * Setter for <code>public.function3_2.speechcontext</code>.
     */
    public Function3_2 setSpeechcontext(String speechcontext) {
        this.speechcontext = speechcontext;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Function3_2 other = (Function3_2) obj;
        if (this.speechcode == null) {
            if (other.speechcode != null)
                return false;
        }
        else if (!this.speechcode.equals(other.speechcode))
            return false;
        if (this.speechcontext == null) {
            if (other.speechcontext != null)
                return false;
        }
        else if (!this.speechcontext.equals(other.speechcontext))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.speechcode == null) ? 0 : this.speechcode.hashCode());
        result = prime * result + ((this.speechcontext == null) ? 0 : this.speechcontext.hashCode());
        return result;
    }
}
