/*
 * This file is generated by jOOQ.
 */
package kr.co.ihab.speechear.persistence.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Function5_1 implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer index;
    private Integer col;
    private Integer row;
    private Integer cnt;
    private String nullpoint;
    private String a;
    private String b;
    private String c;
    private String d;
    private String e;
    private String vertical;
    private String horizontal;
    private String existpoint;
    private String context;

    public Function5_1() {}

    public Function5_1(Function5_1 value) {
        this.index = value.index;
        this.col = value.col;
        this.row = value.row;
        this.cnt = value.cnt;
        this.nullpoint = value.nullpoint;
        this.a = value.a;
        this.b = value.b;
        this.c = value.c;
        this.d = value.d;
        this.e = value.e;
        this.vertical = value.vertical;
        this.horizontal = value.horizontal;
        this.existpoint = value.existpoint;
        this.context = value.context;
    }

    public Function5_1(
        Integer index,
        Integer col,
        Integer row,
        Integer cnt,
        String nullpoint,
        String a,
        String b,
        String c,
        String d,
        String e,
        String vertical,
        String horizontal,
        String existpoint,
        String context
    ) {
        this.index = index;
        this.col = col;
        this.row = row;
        this.cnt = cnt;
        this.nullpoint = nullpoint;
        this.a = a;
        this.b = b;
        this.c = c;
        this.d = d;
        this.e = e;
        this.vertical = vertical;
        this.horizontal = horizontal;
        this.existpoint = existpoint;
        this.context = context;
    }

    /**
     * Getter for <code>public.function5_1.index</code>.
     */
    public Integer getIndex() {
        return this.index;
    }

    /**
     * Setter for <code>public.function5_1.index</code>.
     */
    public Function5_1 setIndex(Integer index) {
        this.index = index;
        return this;
    }

    /**
     * Getter for <code>public.function5_1.col</code>.
     */
    public Integer getCol() {
        return this.col;
    }

    /**
     * Setter for <code>public.function5_1.col</code>.
     */
    public Function5_1 setCol(Integer col) {
        this.col = col;
        return this;
    }

    /**
     * Getter for <code>public.function5_1.row</code>.
     */
    public Integer getRow() {
        return this.row;
    }

    /**
     * Setter for <code>public.function5_1.row</code>.
     */
    public Function5_1 setRow(Integer row) {
        this.row = row;
        return this;
    }

    /**
     * Getter for <code>public.function5_1.cnt</code>.
     */
    public Integer getCnt() {
        return this.cnt;
    }

    /**
     * Setter for <code>public.function5_1.cnt</code>.
     */
    public Function5_1 setCnt(Integer cnt) {
        this.cnt = cnt;
        return this;
    }

    /**
     * Getter for <code>public.function5_1.nullpoint</code>.
     */
    public String getNullpoint() {
        return this.nullpoint;
    }

    /**
     * Setter for <code>public.function5_1.nullpoint</code>.
     */
    public Function5_1 setNullpoint(String nullpoint) {
        this.nullpoint = nullpoint;
        return this;
    }

    /**
     * Getter for <code>public.function5_1.a</code>.
     */
    public String getA() {
        return this.a;
    }

    /**
     * Setter for <code>public.function5_1.a</code>.
     */
    public Function5_1 setA(String a) {
        this.a = a;
        return this;
    }

    /**
     * Getter for <code>public.function5_1.b</code>.
     */
    public String getB() {
        return this.b;
    }

    /**
     * Setter for <code>public.function5_1.b</code>.
     */
    public Function5_1 setB(String b) {
        this.b = b;
        return this;
    }

    /**
     * Getter for <code>public.function5_1.c</code>.
     */
    public String getC() {
        return this.c;
    }

    /**
     * Setter for <code>public.function5_1.c</code>.
     */
    public Function5_1 setC(String c) {
        this.c = c;
        return this;
    }

    /**
     * Getter for <code>public.function5_1.d</code>.
     */
    public String getD() {
        return this.d;
    }

    /**
     * Setter for <code>public.function5_1.d</code>.
     */
    public Function5_1 setD(String d) {
        this.d = d;
        return this;
    }

    /**
     * Getter for <code>public.function5_1.e</code>.
     */
    public String getE() {
        return this.e;
    }

    /**
     * Setter for <code>public.function5_1.e</code>.
     */
    public Function5_1 setE(String e) {
        this.e = e;
        return this;
    }

    /**
     * Getter for <code>public.function5_1.vertical</code>.
     */
    public String getVertical() {
        return this.vertical;
    }

    /**
     * Setter for <code>public.function5_1.vertical</code>.
     */
    public Function5_1 setVertical(String vertical) {
        this.vertical = vertical;
        return this;
    }

    /**
     * Getter for <code>public.function5_1.horizontal</code>.
     */
    public String getHorizontal() {
        return this.horizontal;
    }

    /**
     * Setter for <code>public.function5_1.horizontal</code>.
     */
    public Function5_1 setHorizontal(String horizontal) {
        this.horizontal = horizontal;
        return this;
    }

    /**
     * Getter for <code>public.function5_1.existpoint</code>.
     */
    public String getExistpoint() {
        return this.existpoint;
    }

    /**
     * Setter for <code>public.function5_1.existpoint</code>.
     */
    public Function5_1 setExistpoint(String existpoint) {
        this.existpoint = existpoint;
        return this;
    }

    /**
     * Getter for <code>public.function5_1.context</code>.
     */
    public String getContext() {
        return this.context;
    }

    /**
     * Setter for <code>public.function5_1.context</code>.
     */
    public Function5_1 setContext(String context) {
        this.context = context;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Function5_1 other = (Function5_1) obj;
        if (this.index == null) {
            if (other.index != null)
                return false;
        }
        else if (!this.index.equals(other.index))
            return false;
        if (this.col == null) {
            if (other.col != null)
                return false;
        }
        else if (!this.col.equals(other.col))
            return false;
        if (this.row == null) {
            if (other.row != null)
                return false;
        }
        else if (!this.row.equals(other.row))
            return false;
        if (this.cnt == null) {
            if (other.cnt != null)
                return false;
        }
        else if (!this.cnt.equals(other.cnt))
            return false;
        if (this.nullpoint == null) {
            if (other.nullpoint != null)
                return false;
        }
        else if (!this.nullpoint.equals(other.nullpoint))
            return false;
        if (this.a == null) {
            if (other.a != null)
                return false;
        }
        else if (!this.a.equals(other.a))
            return false;
        if (this.b == null) {
            if (other.b != null)
                return false;
        }
        else if (!this.b.equals(other.b))
            return false;
        if (this.c == null) {
            if (other.c != null)
                return false;
        }
        else if (!this.c.equals(other.c))
            return false;
        if (this.d == null) {
            if (other.d != null)
                return false;
        }
        else if (!this.d.equals(other.d))
            return false;
        if (this.e == null) {
            if (other.e != null)
                return false;
        }
        else if (!this.e.equals(other.e))
            return false;
        if (this.vertical == null) {
            if (other.vertical != null)
                return false;
        }
        else if (!this.vertical.equals(other.vertical))
            return false;
        if (this.horizontal == null) {
            if (other.horizontal != null)
                return false;
        }
        else if (!this.horizontal.equals(other.horizontal))
            return false;
        if (this.existpoint == null) {
            if (other.existpoint != null)
                return false;
        }
        else if (!this.existpoint.equals(other.existpoint))
            return false;
        if (this.context == null) {
            if (other.context != null)
                return false;
        }
        else if (!this.context.equals(other.context))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.index == null) ? 0 : this.index.hashCode());
        result = prime * result + ((this.col == null) ? 0 : this.col.hashCode());
        result = prime * result + ((this.row == null) ? 0 : this.row.hashCode());
        result = prime * result + ((this.cnt == null) ? 0 : this.cnt.hashCode());
        result = prime * result + ((this.nullpoint == null) ? 0 : this.nullpoint.hashCode());
        result = prime * result + ((this.a == null) ? 0 : this.a.hashCode());
        result = prime * result + ((this.b == null) ? 0 : this.b.hashCode());
        result = prime * result + ((this.c == null) ? 0 : this.c.hashCode());
        result = prime * result + ((this.d == null) ? 0 : this.d.hashCode());
        result = prime * result + ((this.e == null) ? 0 : this.e.hashCode());
        result = prime * result + ((this.vertical == null) ? 0 : this.vertical.hashCode());
        result = prime * result + ((this.horizontal == null) ? 0 : this.horizontal.hashCode());
        result = prime * result + ((this.existpoint == null) ? 0 : this.existpoint.hashCode());
        result = prime * result + ((this.context == null) ? 0 : this.context.hashCode());
        return result;
    }
}
