/*
 * This file is generated by jOOQ.
 */
package kr.co.ihab.speechear.persistence.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoleInfo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String name;

    public RoleInfo() {}

    public RoleInfo(RoleInfo value) {
        this.id = value.id;
        this.name = value.name;
    }

    public RoleInfo(
        Long id,
        String name
    ) {
        this.id = id;
        this.name = name;
    }

    /**
     * Getter for <code>public.role_info.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.role_info.id</code>.
     */
    public RoleInfo setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.role_info.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.role_info.name</code>.
     */
    public RoleInfo setName(String name) {
        this.name = name;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final RoleInfo other = (RoleInfo) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        return result;
    }
}
