/*
 * This file is generated by jOOQ.
 */
package kr.co.ihab.speechear.persistence.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserSetting implements Serializable {

    private static final long serialVersionUID = 1L;

    private String userId;
    private String noiseType;
    private String playSpeed;

    public UserSetting() {}

    public UserSetting(UserSetting value) {
        this.userId = value.userId;
        this.noiseType = value.noiseType;
        this.playSpeed = value.playSpeed;
    }

    public UserSetting(
        String userId,
        String noiseType,
        String playSpeed
    ) {
        this.userId = userId;
        this.noiseType = noiseType;
        this.playSpeed = playSpeed;
    }

    /**
     * Getter for <code>public.user_setting.user_id</code>.
     */
    public String getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>public.user_setting.user_id</code>.
     */
    public UserSetting setUserId(String userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Getter for <code>public.user_setting.noise_type</code>.
     */
    public String getNoiseType() {
        return this.noiseType;
    }

    /**
     * Setter for <code>public.user_setting.noise_type</code>.
     */
    public UserSetting setNoiseType(String noiseType) {
        this.noiseType = noiseType;
        return this;
    }

    /**
     * Getter for <code>public.user_setting.play_speed</code>.
     */
    public String getPlaySpeed() {
        return this.playSpeed;
    }

    /**
     * Setter for <code>public.user_setting.play_speed</code>.
     */
    public UserSetting setPlaySpeed(String playSpeed) {
        this.playSpeed = playSpeed;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserSetting other = (UserSetting) obj;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.noiseType == null) {
            if (other.noiseType != null)
                return false;
        }
        else if (!this.noiseType.equals(other.noiseType))
            return false;
        if (this.playSpeed == null) {
            if (other.playSpeed != null)
                return false;
        }
        else if (!this.playSpeed.equals(other.playSpeed))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.noiseType == null) ? 0 : this.noiseType.hashCode());
        result = prime * result + ((this.playSpeed == null) ? 0 : this.playSpeed.hashCode());
        return result;
    }
}
