/*
 * This file is generated by jOOQ.
 */
package kr.co.ihab.speechear.persistence.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserLog implements Serializable {

    private static final long serialVersionUID = 1L;

    private String accessIp;
    private String accessId;
    private String accessTime;
    private String accessRole;
    private String accessUri;

    public UserLog() {}

    public UserLog(UserLog value) {
        this.accessIp = value.accessIp;
        this.accessId = value.accessId;
        this.accessTime = value.accessTime;
        this.accessRole = value.accessRole;
        this.accessUri = value.accessUri;
    }

    public UserLog(
        String accessIp,
        String accessId,
        String accessTime,
        String accessRole,
        String accessUri
    ) {
        this.accessIp = accessIp;
        this.accessId = accessId;
        this.accessTime = accessTime;
        this.accessRole = accessRole;
        this.accessUri = accessUri;
    }

    /**
     * Getter for <code>public.user_log.access_ip</code>.
     */
    public String getAccessIp() {
        return this.accessIp;
    }

    /**
     * Setter for <code>public.user_log.access_ip</code>.
     */
    public UserLog setAccessIp(String accessIp) {
        this.accessIp = accessIp;
        return this;
    }

    /**
     * Getter for <code>public.user_log.access_id</code>.
     */
    public String getAccessId() {
        return this.accessId;
    }

    /**
     * Setter for <code>public.user_log.access_id</code>.
     */
    public UserLog setAccessId(String accessId) {
        this.accessId = accessId;
        return this;
    }

    /**
     * Getter for <code>public.user_log.access_time</code>.
     */
    public String getAccessTime() {
        return this.accessTime;
    }

    /**
     * Setter for <code>public.user_log.access_time</code>.
     */
    public UserLog setAccessTime(String accessTime) {
        this.accessTime = accessTime;
        return this;
    }

    /**
     * Getter for <code>public.user_log.access_role</code>.
     */
    public String getAccessRole() {
        return this.accessRole;
    }

    /**
     * Setter for <code>public.user_log.access_role</code>.
     */
    public UserLog setAccessRole(String accessRole) {
        this.accessRole = accessRole;
        return this;
    }

    /**
     * Getter for <code>public.user_log.access_uri</code>.
     */
    public String getAccessUri() {
        return this.accessUri;
    }

    /**
     * Setter for <code>public.user_log.access_uri</code>.
     */
    public UserLog setAccessUri(String accessUri) {
        this.accessUri = accessUri;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserLog other = (UserLog) obj;
        if (this.accessIp == null) {
            if (other.accessIp != null)
                return false;
        }
        else if (!this.accessIp.equals(other.accessIp))
            return false;
        if (this.accessId == null) {
            if (other.accessId != null)
                return false;
        }
        else if (!this.accessId.equals(other.accessId))
            return false;
        if (this.accessTime == null) {
            if (other.accessTime != null)
                return false;
        }
        else if (!this.accessTime.equals(other.accessTime))
            return false;
        if (this.accessRole == null) {
            if (other.accessRole != null)
                return false;
        }
        else if (!this.accessRole.equals(other.accessRole))
            return false;
        if (this.accessUri == null) {
            if (other.accessUri != null)
                return false;
        }
        else if (!this.accessUri.equals(other.accessUri))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.accessIp == null) ? 0 : this.accessIp.hashCode());
        result = prime * result + ((this.accessId == null) ? 0 : this.accessId.hashCode());
        result = prime * result + ((this.accessTime == null) ? 0 : this.accessTime.hashCode());
        result = prime * result + ((this.accessRole == null) ? 0 : this.accessRole.hashCode());
        result = prime * result + ((this.accessUri == null) ? 0 : this.accessUri.hashCode());
        return result;
    }
}
