/*
 * This file is generated by jOOQ.
 */
package kr.co.ihab.speechear.persistence.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserAssignment implements Serializable {

    private static final long serialVersionUID = 1L;

    private String id;
    private String manager;

    public UserAssignment() {}

    public UserAssignment(UserAssignment value) {
        this.id = value.id;
        this.manager = value.manager;
    }

    public UserAssignment(
        String id,
        String manager
    ) {
        this.id = id;
        this.manager = manager;
    }

    /**
     * Getter for <code>public.user_assignment.id</code>.
     */
    public String getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.user_assignment.id</code>.
     */
    public UserAssignment setId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.user_assignment.manager</code>.
     */
    public String getManager() {
        return this.manager;
    }

    /**
     * Setter for <code>public.user_assignment.manager</code>.
     */
    public UserAssignment setManager(String manager) {
        this.manager = manager;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserAssignment other = (UserAssignment) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.manager == null) {
            if (other.manager != null)
                return false;
        }
        else if (!this.manager.equals(other.manager))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.manager == null) ? 0 : this.manager.hashCode());
        return result;
    }
}
