/*
 * This file is generated by jOOQ.
 */
package kr.co.ihab.speechear.persistence.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserTrainingChapter implements Serializable {

    private static final long serialVersionUID = 1L;

    private String trainingId;
    private String trainingCategory;
    private Integer trainingChapter;
    private Integer chapterLength;

    public UserTrainingChapter() {}

    public UserTrainingChapter(UserTrainingChapter value) {
        this.trainingId = value.trainingId;
        this.trainingCategory = value.trainingCategory;
        this.trainingChapter = value.trainingChapter;
        this.chapterLength = value.chapterLength;
    }

    public UserTrainingChapter(
        String trainingId,
        String trainingCategory,
        Integer trainingChapter,
        Integer chapterLength
    ) {
        this.trainingId = trainingId;
        this.trainingCategory = trainingCategory;
        this.trainingChapter = trainingChapter;
        this.chapterLength = chapterLength;
    }

    /**
     * Getter for <code>public.user_training_chapter.training_id</code>.
     */
    public String getTrainingId() {
        return this.trainingId;
    }

    /**
     * Setter for <code>public.user_training_chapter.training_id</code>.
     */
    public UserTrainingChapter setTrainingId(String trainingId) {
        this.trainingId = trainingId;
        return this;
    }

    /**
     * Getter for <code>public.user_training_chapter.training_category</code>.
     */
    public String getTrainingCategory() {
        return this.trainingCategory;
    }

    /**
     * Setter for <code>public.user_training_chapter.training_category</code>.
     */
    public UserTrainingChapter setTrainingCategory(String trainingCategory) {
        this.trainingCategory = trainingCategory;
        return this;
    }

    /**
     * Getter for <code>public.user_training_chapter.training_chapter</code>.
     */
    public Integer getTrainingChapter() {
        return this.trainingChapter;
    }

    /**
     * Setter for <code>public.user_training_chapter.training_chapter</code>.
     */
    public UserTrainingChapter setTrainingChapter(Integer trainingChapter) {
        this.trainingChapter = trainingChapter;
        return this;
    }

    /**
     * Getter for <code>public.user_training_chapter.chapter_length</code>.
     */
    public Integer getChapterLength() {
        return this.chapterLength;
    }

    /**
     * Setter for <code>public.user_training_chapter.chapter_length</code>.
     */
    public UserTrainingChapter setChapterLength(Integer chapterLength) {
        this.chapterLength = chapterLength;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserTrainingChapter other = (UserTrainingChapter) obj;
        if (this.trainingId == null) {
            if (other.trainingId != null)
                return false;
        }
        else if (!this.trainingId.equals(other.trainingId))
            return false;
        if (this.trainingCategory == null) {
            if (other.trainingCategory != null)
                return false;
        }
        else if (!this.trainingCategory.equals(other.trainingCategory))
            return false;
        if (this.trainingChapter == null) {
            if (other.trainingChapter != null)
                return false;
        }
        else if (!this.trainingChapter.equals(other.trainingChapter))
            return false;
        if (this.chapterLength == null) {
            if (other.chapterLength != null)
                return false;
        }
        else if (!this.chapterLength.equals(other.chapterLength))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.trainingId == null) ? 0 : this.trainingId.hashCode());
        result = prime * result + ((this.trainingCategory == null) ? 0 : this.trainingCategory.hashCode());
        result = prime * result + ((this.trainingChapter == null) ? 0 : this.trainingChapter.hashCode());
        result = prime * result + ((this.chapterLength == null) ? 0 : this.chapterLength.hashCode());
        return result;
    }
}
