/*
 * This file is generated by jOOQ.
 */
package kr.co.ihab.speechear.persistence.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserTrainingType implements Serializable {

    private static final long serialVersionUID = 1L;

    private String trainingId;
    private String trainingName;

    public UserTrainingType() {}

    public UserTrainingType(UserTrainingType value) {
        this.trainingId = value.trainingId;
        this.trainingName = value.trainingName;
    }

    public UserTrainingType(
        String trainingId,
        String trainingName
    ) {
        this.trainingId = trainingId;
        this.trainingName = trainingName;
    }

    /**
     * Getter for <code>public.user_training_type.training_id</code>.
     */
    public String getTrainingId() {
        return this.trainingId;
    }

    /**
     * Setter for <code>public.user_training_type.training_id</code>.
     */
    public UserTrainingType setTrainingId(String trainingId) {
        this.trainingId = trainingId;
        return this;
    }

    /**
     * Getter for <code>public.user_training_type.training_name</code>.
     */
    public String getTrainingName() {
        return this.trainingName;
    }

    /**
     * Setter for <code>public.user_training_type.training_name</code>.
     */
    public UserTrainingType setTrainingName(String trainingName) {
        this.trainingName = trainingName;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserTrainingType other = (UserTrainingType) obj;
        if (this.trainingId == null) {
            if (other.trainingId != null)
                return false;
        }
        else if (!this.trainingId.equals(other.trainingId))
            return false;
        if (this.trainingName == null) {
            if (other.trainingName != null)
                return false;
        }
        else if (!this.trainingName.equals(other.trainingName))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.trainingId == null) ? 0 : this.trainingId.hashCode());
        result = prime * result + ((this.trainingName == null) ? 0 : this.trainingName.hashCode());
        return result;
    }
}
