/*
 * This file is generated by jOOQ.
 */
package kr.co.ihab.speechear.persistence.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserInfo implements Serializable {

    private static final long serialVersionUID = 1L;

    private String id;
    private String password;
    private String name;
    private String email;
    private String cellphone;

    public UserInfo() {}

    public UserInfo(UserInfo value) {
        this.id = value.id;
        this.password = value.password;
        this.name = value.name;
        this.email = value.email;
        this.cellphone = value.cellphone;
    }

    public UserInfo(
        String id,
        String password,
        String name,
        String email,
        String cellphone
    ) {
        this.id = id;
        this.password = password;
        this.name = name;
        this.email = email;
        this.cellphone = cellphone;
    }

    /**
     * Getter for <code>public.user_info.id</code>.
     */
    public String getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.user_info.id</code>.
     */
    public UserInfo setId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.user_info.password</code>.
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>public.user_info.password</code>.
     */
    public UserInfo setPassword(String password) {
        this.password = password;
        return this;
    }

    /**
     * Getter for <code>public.user_info.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.user_info.name</code>.
     */
    public UserInfo setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>public.user_info.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>public.user_info.email</code>.
     */
    public UserInfo setEmail(String email) {
        this.email = email;
        return this;
    }

    /**
     * Getter for <code>public.user_info.cellphone</code>.
     */
    public String getCellphone() {
        return this.cellphone;
    }

    /**
     * Setter for <code>public.user_info.cellphone</code>.
     */
    public UserInfo setCellphone(String cellphone) {
        this.cellphone = cellphone;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserInfo other = (UserInfo) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.password == null) {
            if (other.password != null)
                return false;
        }
        else if (!this.password.equals(other.password))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.email == null) {
            if (other.email != null)
                return false;
        }
        else if (!this.email.equals(other.email))
            return false;
        if (this.cellphone == null) {
            if (other.cellphone != null)
                return false;
        }
        else if (!this.cellphone.equals(other.cellphone))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.password == null) ? 0 : this.password.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.cellphone == null) ? 0 : this.cellphone.hashCode());
        return result;
    }
}
