/*
 * This file is generated by jOOQ.
 */
package kr.co.ihab.speechear.persistence.jooq.tables.records;


import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import kr.co.ihab.speechear.persistence.jooq.tables.FileInfo;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FileInfoRecord extends TableRecordImpl<FileInfoRecord> implements Record5<String, String, LocalDateTime, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.file_info.name</code>.
     */
    public FileInfoRecord setName(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.file_info.name</code>.
     */
    public String getName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.file_info.extension</code>.
     */
    public FileInfoRecord setExtension(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.file_info.extension</code>.
     */
    public String getExtension() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.file_info.date_created</code>.
     */
    public FileInfoRecord setDateCreated(LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.file_info.date_created</code>.
     */
    public LocalDateTime getDateCreated() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.file_info.file_path</code>.
     */
    public FileInfoRecord setFilePath(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.file_info.file_path</code>.
     */
    public String getFilePath() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.file_info.date_modified</code>.
     */
    public FileInfoRecord setDateModified(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.file_info.date_modified</code>.
     */
    public LocalDateTime getDateModified() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<String, String, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<String, String, LocalDateTime, String, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return FileInfo.FILE_INFO.NAME;
    }

    @Override
    public Field<String> field2() {
        return FileInfo.FILE_INFO.EXTENSION;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return FileInfo.FILE_INFO.DATE_CREATED;
    }

    @Override
    public Field<String> field4() {
        return FileInfo.FILE_INFO.FILE_PATH;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return FileInfo.FILE_INFO.DATE_MODIFIED;
    }

    @Override
    public String component1() {
        return getName();
    }

    @Override
    public String component2() {
        return getExtension();
    }

    @Override
    public LocalDateTime component3() {
        return getDateCreated();
    }

    @Override
    public String component4() {
        return getFilePath();
    }

    @Override
    public LocalDateTime component5() {
        return getDateModified();
    }

    @Override
    public String value1() {
        return getName();
    }

    @Override
    public String value2() {
        return getExtension();
    }

    @Override
    public LocalDateTime value3() {
        return getDateCreated();
    }

    @Override
    public String value4() {
        return getFilePath();
    }

    @Override
    public LocalDateTime value5() {
        return getDateModified();
    }

    @Override
    public FileInfoRecord value1(String value) {
        setName(value);
        return this;
    }

    @Override
    public FileInfoRecord value2(String value) {
        setExtension(value);
        return this;
    }

    @Override
    public FileInfoRecord value3(LocalDateTime value) {
        setDateCreated(value);
        return this;
    }

    @Override
    public FileInfoRecord value4(String value) {
        setFilePath(value);
        return this;
    }

    @Override
    public FileInfoRecord value5(LocalDateTime value) {
        setDateModified(value);
        return this;
    }

    @Override
    public FileInfoRecord values(String value1, String value2, LocalDateTime value3, String value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FileInfoRecord
     */
    public FileInfoRecord() {
        super(FileInfo.FILE_INFO);
    }

    /**
     * Create a detached, initialised FileInfoRecord
     */
    public FileInfoRecord(String name, String extension, LocalDateTime dateCreated, String filePath, LocalDateTime dateModified) {
        super(FileInfo.FILE_INFO);

        setName(name);
        setExtension(extension);
        setDateCreated(dateCreated);
        setFilePath(filePath);
        setDateModified(dateModified);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised FileInfoRecord
     */
    public FileInfoRecord(kr.co.ihab.speechear.persistence.jooq.tables.pojos.FileInfo value) {
        super(FileInfo.FILE_INFO);

        if (value != null) {
            setName(value.getName());
            setExtension(value.getExtension());
            setDateCreated(value.getDateCreated());
            setFilePath(value.getFilePath());
            setDateModified(value.getDateModified());
            resetChangedOnNotNull();
        }
    }
}
