/*
 * This file is generated by jOOQ.
 */
package kr.co.ihab.speechear.persistence.jooq.tables.records;


import javax.annotation.processing.Generated;

import kr.co.ihab.speechear.persistence.jooq.tables.Function5_2;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Function5_2Record extends TableRecordImpl<Function5_2Record> implements Record2<String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.function5_2.filename</code>.
     */
    public Function5_2Record setFilename(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.function5_2.filename</code>.
     */
    public String getFilename() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.function5_2.context</code>.
     */
    public Function5_2Record setContext(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.function5_2.context</code>.
     */
    public String getContext() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Function5_2.FUNCTION5_2.FILENAME;
    }

    @Override
    public Field<String> field2() {
        return Function5_2.FUNCTION5_2.CONTEXT;
    }

    @Override
    public String component1() {
        return getFilename();
    }

    @Override
    public String component2() {
        return getContext();
    }

    @Override
    public String value1() {
        return getFilename();
    }

    @Override
    public String value2() {
        return getContext();
    }

    @Override
    public Function5_2Record value1(String value) {
        setFilename(value);
        return this;
    }

    @Override
    public Function5_2Record value2(String value) {
        setContext(value);
        return this;
    }

    @Override
    public Function5_2Record values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached Function5_2Record
     */
    public Function5_2Record() {
        super(Function5_2.FUNCTION5_2);
    }

    /**
     * Create a detached, initialised Function5_2Record
     */
    public Function5_2Record(String filename, String context) {
        super(Function5_2.FUNCTION5_2);

        setFilename(filename);
        setContext(context);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised Function5_2Record
     */
    public Function5_2Record(kr.co.ihab.speechear.persistence.jooq.tables.pojos.Function5_2 value) {
        super(Function5_2.FUNCTION5_2);

        if (value != null) {
            setFilename(value.getFilename());
            setContext(value.getContext());
            resetChangedOnNotNull();
        }
    }
}
