/*
 * This file is generated by jOOQ.
 */
package kr.co.ihab.speechear.persistence.jooq.tables.records;


import javax.annotation.processing.Generated;

import kr.co.ihab.speechear.persistence.jooq.tables.Function3_2;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Function3_2Record extends TableRecordImpl<Function3_2Record> implements Record2<String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.function3_2.speechcode</code>.
     */
    public Function3_2Record setSpeechcode(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.function3_2.speechcode</code>.
     */
    public String getSpeechcode() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.function3_2.speechcontext</code>.
     */
    public Function3_2Record setSpeechcontext(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.function3_2.speechcontext</code>.
     */
    public String getSpeechcontext() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Function3_2.FUNCTION3_2.SPEECHCODE;
    }

    @Override
    public Field<String> field2() {
        return Function3_2.FUNCTION3_2.SPEECHCONTEXT;
    }

    @Override
    public String component1() {
        return getSpeechcode();
    }

    @Override
    public String component2() {
        return getSpeechcontext();
    }

    @Override
    public String value1() {
        return getSpeechcode();
    }

    @Override
    public String value2() {
        return getSpeechcontext();
    }

    @Override
    public Function3_2Record value1(String value) {
        setSpeechcode(value);
        return this;
    }

    @Override
    public Function3_2Record value2(String value) {
        setSpeechcontext(value);
        return this;
    }

    @Override
    public Function3_2Record values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached Function3_2Record
     */
    public Function3_2Record() {
        super(Function3_2.FUNCTION3_2);
    }

    /**
     * Create a detached, initialised Function3_2Record
     */
    public Function3_2Record(String speechcode, String speechcontext) {
        super(Function3_2.FUNCTION3_2);

        setSpeechcode(speechcode);
        setSpeechcontext(speechcontext);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised Function3_2Record
     */
    public Function3_2Record(kr.co.ihab.speechear.persistence.jooq.tables.pojos.Function3_2 value) {
        super(Function3_2.FUNCTION3_2);

        if (value != null) {
            setSpeechcode(value.getSpeechcode());
            setSpeechcontext(value.getSpeechcontext());
            resetChangedOnNotNull();
        }
    }
}
