/*
 * This file is generated by jOOQ.
 */
package kr.co.ihab.speechear.persistence.jooq.tables.records;


import javax.annotation.processing.Generated;

import kr.co.ihab.speechear.persistence.jooq.tables.Function3_1;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Function3_1Record extends TableRecordImpl<Function3_1Record> implements Record4<String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.function3_1.speechcode</code>.
     */
    public Function3_1Record setSpeechcode(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.function3_1.speechcode</code>.
     */
    public String getSpeechcode() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.function3_1.questioncode</code>.
     */
    public Function3_1Record setQuestioncode(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.function3_1.questioncode</code>.
     */
    public String getQuestioncode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.function3_1.questioncontext</code>.
     */
    public Function3_1Record setQuestioncontext(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.function3_1.questioncontext</code>.
     */
    public String getQuestioncontext() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.function3_1.answer</code>.
     */
    public Function3_1Record setAnswer(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.function3_1.answer</code>.
     */
    public String getAnswer() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<String, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Function3_1.FUNCTION3_1.SPEECHCODE;
    }

    @Override
    public Field<String> field2() {
        return Function3_1.FUNCTION3_1.QUESTIONCODE;
    }

    @Override
    public Field<String> field3() {
        return Function3_1.FUNCTION3_1.QUESTIONCONTEXT;
    }

    @Override
    public Field<String> field4() {
        return Function3_1.FUNCTION3_1.ANSWER;
    }

    @Override
    public String component1() {
        return getSpeechcode();
    }

    @Override
    public String component2() {
        return getQuestioncode();
    }

    @Override
    public String component3() {
        return getQuestioncontext();
    }

    @Override
    public String component4() {
        return getAnswer();
    }

    @Override
    public String value1() {
        return getSpeechcode();
    }

    @Override
    public String value2() {
        return getQuestioncode();
    }

    @Override
    public String value3() {
        return getQuestioncontext();
    }

    @Override
    public String value4() {
        return getAnswer();
    }

    @Override
    public Function3_1Record value1(String value) {
        setSpeechcode(value);
        return this;
    }

    @Override
    public Function3_1Record value2(String value) {
        setQuestioncode(value);
        return this;
    }

    @Override
    public Function3_1Record value3(String value) {
        setQuestioncontext(value);
        return this;
    }

    @Override
    public Function3_1Record value4(String value) {
        setAnswer(value);
        return this;
    }

    @Override
    public Function3_1Record values(String value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached Function3_1Record
     */
    public Function3_1Record() {
        super(Function3_1.FUNCTION3_1);
    }

    /**
     * Create a detached, initialised Function3_1Record
     */
    public Function3_1Record(String speechcode, String questioncode, String questioncontext, String answer) {
        super(Function3_1.FUNCTION3_1);

        setSpeechcode(speechcode);
        setQuestioncode(questioncode);
        setQuestioncontext(questioncontext);
        setAnswer(answer);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised Function3_1Record
     */
    public Function3_1Record(kr.co.ihab.speechear.persistence.jooq.tables.pojos.Function3_1 value) {
        super(Function3_1.FUNCTION3_1);

        if (value != null) {
            setSpeechcode(value.getSpeechcode());
            setQuestioncode(value.getQuestioncode());
            setQuestioncontext(value.getQuestioncontext());
            setAnswer(value.getAnswer());
            resetChangedOnNotNull();
        }
    }
}
