/*
 * This file is generated by jOOQ.
 */
package kr.co.ihab.speechear.persistence.jooq.tables.records;


import javax.annotation.processing.Generated;

import kr.co.ihab.speechear.persistence.jooq.tables.Function5_1;

import org.jooq.Field;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Function5_1Record extends TableRecordImpl<Function5_1Record> implements Record14<Integer, Integer, Integer, Integer, String, String, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.function5_1.index</code>.
     */
    public Function5_1Record setIndex(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.function5_1.index</code>.
     */
    public Integer getIndex() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.function5_1.col</code>.
     */
    public Function5_1Record setCol(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.function5_1.col</code>.
     */
    public Integer getCol() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.function5_1.row</code>.
     */
    public Function5_1Record setRow(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.function5_1.row</code>.
     */
    public Integer getRow() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.function5_1.cnt</code>.
     */
    public Function5_1Record setCnt(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.function5_1.cnt</code>.
     */
    public Integer getCnt() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.function5_1.nullpoint</code>.
     */
    public Function5_1Record setNullpoint(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.function5_1.nullpoint</code>.
     */
    public String getNullpoint() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.function5_1.a</code>.
     */
    public Function5_1Record setA(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.function5_1.a</code>.
     */
    public String getA() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.function5_1.b</code>.
     */
    public Function5_1Record setB(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.function5_1.b</code>.
     */
    public String getB() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.function5_1.c</code>.
     */
    public Function5_1Record setC(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.function5_1.c</code>.
     */
    public String getC() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.function5_1.d</code>.
     */
    public Function5_1Record setD(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.function5_1.d</code>.
     */
    public String getD() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.function5_1.e</code>.
     */
    public Function5_1Record setE(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.function5_1.e</code>.
     */
    public String getE() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.function5_1.vertical</code>.
     */
    public Function5_1Record setVertical(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.function5_1.vertical</code>.
     */
    public String getVertical() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.function5_1.horizontal</code>.
     */
    public Function5_1Record setHorizontal(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.function5_1.horizontal</code>.
     */
    public String getHorizontal() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.function5_1.existpoint</code>.
     */
    public Function5_1Record setExistpoint(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.function5_1.existpoint</code>.
     */
    public String getExistpoint() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.function5_1.context</code>.
     */
    public Function5_1Record setContext(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>public.function5_1.context</code>.
     */
    public String getContext() {
        return (String) get(13);
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row14<Integer, Integer, Integer, Integer, String, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    @Override
    public Row14<Integer, Integer, Integer, Integer, String, String, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row14) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Function5_1.FUNCTION5_1.INDEX;
    }

    @Override
    public Field<Integer> field2() {
        return Function5_1.FUNCTION5_1.COL;
    }

    @Override
    public Field<Integer> field3() {
        return Function5_1.FUNCTION5_1.ROW;
    }

    @Override
    public Field<Integer> field4() {
        return Function5_1.FUNCTION5_1.CNT;
    }

    @Override
    public Field<String> field5() {
        return Function5_1.FUNCTION5_1.NULLPOINT;
    }

    @Override
    public Field<String> field6() {
        return Function5_1.FUNCTION5_1.A;
    }

    @Override
    public Field<String> field7() {
        return Function5_1.FUNCTION5_1.B;
    }

    @Override
    public Field<String> field8() {
        return Function5_1.FUNCTION5_1.C;
    }

    @Override
    public Field<String> field9() {
        return Function5_1.FUNCTION5_1.D;
    }

    @Override
    public Field<String> field10() {
        return Function5_1.FUNCTION5_1.E;
    }

    @Override
    public Field<String> field11() {
        return Function5_1.FUNCTION5_1.VERTICAL;
    }

    @Override
    public Field<String> field12() {
        return Function5_1.FUNCTION5_1.HORIZONTAL;
    }

    @Override
    public Field<String> field13() {
        return Function5_1.FUNCTION5_1.EXISTPOINT;
    }

    @Override
    public Field<String> field14() {
        return Function5_1.FUNCTION5_1.CONTEXT;
    }

    @Override
    public Integer component1() {
        return getIndex();
    }

    @Override
    public Integer component2() {
        return getCol();
    }

    @Override
    public Integer component3() {
        return getRow();
    }

    @Override
    public Integer component4() {
        return getCnt();
    }

    @Override
    public String component5() {
        return getNullpoint();
    }

    @Override
    public String component6() {
        return getA();
    }

    @Override
    public String component7() {
        return getB();
    }

    @Override
    public String component8() {
        return getC();
    }

    @Override
    public String component9() {
        return getD();
    }

    @Override
    public String component10() {
        return getE();
    }

    @Override
    public String component11() {
        return getVertical();
    }

    @Override
    public String component12() {
        return getHorizontal();
    }

    @Override
    public String component13() {
        return getExistpoint();
    }

    @Override
    public String component14() {
        return getContext();
    }

    @Override
    public Integer value1() {
        return getIndex();
    }

    @Override
    public Integer value2() {
        return getCol();
    }

    @Override
    public Integer value3() {
        return getRow();
    }

    @Override
    public Integer value4() {
        return getCnt();
    }

    @Override
    public String value5() {
        return getNullpoint();
    }

    @Override
    public String value6() {
        return getA();
    }

    @Override
    public String value7() {
        return getB();
    }

    @Override
    public String value8() {
        return getC();
    }

    @Override
    public String value9() {
        return getD();
    }

    @Override
    public String value10() {
        return getE();
    }

    @Override
    public String value11() {
        return getVertical();
    }

    @Override
    public String value12() {
        return getHorizontal();
    }

    @Override
    public String value13() {
        return getExistpoint();
    }

    @Override
    public String value14() {
        return getContext();
    }

    @Override
    public Function5_1Record value1(Integer value) {
        setIndex(value);
        return this;
    }

    @Override
    public Function5_1Record value2(Integer value) {
        setCol(value);
        return this;
    }

    @Override
    public Function5_1Record value3(Integer value) {
        setRow(value);
        return this;
    }

    @Override
    public Function5_1Record value4(Integer value) {
        setCnt(value);
        return this;
    }

    @Override
    public Function5_1Record value5(String value) {
        setNullpoint(value);
        return this;
    }

    @Override
    public Function5_1Record value6(String value) {
        setA(value);
        return this;
    }

    @Override
    public Function5_1Record value7(String value) {
        setB(value);
        return this;
    }

    @Override
    public Function5_1Record value8(String value) {
        setC(value);
        return this;
    }

    @Override
    public Function5_1Record value9(String value) {
        setD(value);
        return this;
    }

    @Override
    public Function5_1Record value10(String value) {
        setE(value);
        return this;
    }

    @Override
    public Function5_1Record value11(String value) {
        setVertical(value);
        return this;
    }

    @Override
    public Function5_1Record value12(String value) {
        setHorizontal(value);
        return this;
    }

    @Override
    public Function5_1Record value13(String value) {
        setExistpoint(value);
        return this;
    }

    @Override
    public Function5_1Record value14(String value) {
        setContext(value);
        return this;
    }

    @Override
    public Function5_1Record values(Integer value1, Integer value2, Integer value3, Integer value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached Function5_1Record
     */
    public Function5_1Record() {
        super(Function5_1.FUNCTION5_1);
    }

    /**
     * Create a detached, initialised Function5_1Record
     */
    public Function5_1Record(Integer index, Integer col, Integer row, Integer cnt, String nullpoint, String a, String b, String c, String d, String e, String vertical, String horizontal, String existpoint, String context) {
        super(Function5_1.FUNCTION5_1);

        setIndex(index);
        setCol(col);
        setRow(row);
        setCnt(cnt);
        setNullpoint(nullpoint);
        setA(a);
        setB(b);
        setC(c);
        setD(d);
        setE(e);
        setVertical(vertical);
        setHorizontal(horizontal);
        setExistpoint(existpoint);
        setContext(context);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised Function5_1Record
     */
    public Function5_1Record(kr.co.ihab.speechear.persistence.jooq.tables.pojos.Function5_1 value) {
        super(Function5_1.FUNCTION5_1);

        if (value != null) {
            setIndex(value.getIndex());
            setCol(value.getCol());
            setRow(value.getRow());
            setCnt(value.getCnt());
            setNullpoint(value.getNullpoint());
            setA(value.getA());
            setB(value.getB());
            setC(value.getC());
            setD(value.getD());
            setE(value.getE());
            setVertical(value.getVertical());
            setHorizontal(value.getHorizontal());
            setExistpoint(value.getExistpoint());
            setContext(value.getContext());
            resetChangedOnNotNull();
        }
    }
}
