/*
 * This file is generated by jOOQ.
 */
package kr.co.ihab.speechear.persistence.jooq.tables.records;


import javax.annotation.processing.Generated;

import kr.co.ihab.speechear.persistence.jooq.tables.RoleInfo;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoleInfoRecord extends UpdatableRecordImpl<RoleInfoRecord> implements Record2<Long, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.role_info.id</code>.
     */
    public RoleInfoRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.role_info.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.role_info.name</code>.
     */
    public RoleInfoRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.role_info.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return RoleInfo.ROLE_INFO.ID;
    }

    @Override
    public Field<String> field2() {
        return RoleInfo.ROLE_INFO.NAME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public RoleInfoRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public RoleInfoRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public RoleInfoRecord values(Long value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RoleInfoRecord
     */
    public RoleInfoRecord() {
        super(RoleInfo.ROLE_INFO);
    }

    /**
     * Create a detached, initialised RoleInfoRecord
     */
    public RoleInfoRecord(Long id, String name) {
        super(RoleInfo.ROLE_INFO);

        setId(id);
        setName(name);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised RoleInfoRecord
     */
    public RoleInfoRecord(kr.co.ihab.speechear.persistence.jooq.tables.pojos.RoleInfo value) {
        super(RoleInfo.ROLE_INFO);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            resetChangedOnNotNull();
        }
    }
}
