/*
 * This file is generated by jOOQ.
 */
package kr.co.ihab.speechear.persistence.jooq.tables.records;


import javax.annotation.processing.Generated;

import kr.co.ihab.speechear.persistence.jooq.tables.UserLog;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserLogRecord extends TableRecordImpl<UserLogRecord> implements Record5<String, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.user_log.access_ip</code>.
     */
    public UserLogRecord setAccessIp(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.user_log.access_ip</code>.
     */
    public String getAccessIp() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.user_log.access_id</code>.
     */
    public UserLogRecord setAccessId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.user_log.access_id</code>.
     */
    public String getAccessId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.user_log.access_time</code>.
     */
    public UserLogRecord setAccessTime(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.user_log.access_time</code>.
     */
    public String getAccessTime() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.user_log.access_role</code>.
     */
    public UserLogRecord setAccessRole(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.user_log.access_role</code>.
     */
    public String getAccessRole() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.user_log.access_uri</code>.
     */
    public UserLogRecord setAccessUri(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.user_log.access_uri</code>.
     */
    public String getAccessUri() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<String, String, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<String, String, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return UserLog.USER_LOG.ACCESS_IP;
    }

    @Override
    public Field<String> field2() {
        return UserLog.USER_LOG.ACCESS_ID;
    }

    @Override
    public Field<String> field3() {
        return UserLog.USER_LOG.ACCESS_TIME;
    }

    @Override
    public Field<String> field4() {
        return UserLog.USER_LOG.ACCESS_ROLE;
    }

    @Override
    public Field<String> field5() {
        return UserLog.USER_LOG.ACCESS_URI;
    }

    @Override
    public String component1() {
        return getAccessIp();
    }

    @Override
    public String component2() {
        return getAccessId();
    }

    @Override
    public String component3() {
        return getAccessTime();
    }

    @Override
    public String component4() {
        return getAccessRole();
    }

    @Override
    public String component5() {
        return getAccessUri();
    }

    @Override
    public String value1() {
        return getAccessIp();
    }

    @Override
    public String value2() {
        return getAccessId();
    }

    @Override
    public String value3() {
        return getAccessTime();
    }

    @Override
    public String value4() {
        return getAccessRole();
    }

    @Override
    public String value5() {
        return getAccessUri();
    }

    @Override
    public UserLogRecord value1(String value) {
        setAccessIp(value);
        return this;
    }

    @Override
    public UserLogRecord value2(String value) {
        setAccessId(value);
        return this;
    }

    @Override
    public UserLogRecord value3(String value) {
        setAccessTime(value);
        return this;
    }

    @Override
    public UserLogRecord value4(String value) {
        setAccessRole(value);
        return this;
    }

    @Override
    public UserLogRecord value5(String value) {
        setAccessUri(value);
        return this;
    }

    @Override
    public UserLogRecord values(String value1, String value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserLogRecord
     */
    public UserLogRecord() {
        super(UserLog.USER_LOG);
    }

    /**
     * Create a detached, initialised UserLogRecord
     */
    public UserLogRecord(String accessIp, String accessId, String accessTime, String accessRole, String accessUri) {
        super(UserLog.USER_LOG);

        setAccessIp(accessIp);
        setAccessId(accessId);
        setAccessTime(accessTime);
        setAccessRole(accessRole);
        setAccessUri(accessUri);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised UserLogRecord
     */
    public UserLogRecord(kr.co.ihab.speechear.persistence.jooq.tables.pojos.UserLog value) {
        super(UserLog.USER_LOG);

        if (value != null) {
            setAccessIp(value.getAccessIp());
            setAccessId(value.getAccessId());
            setAccessTime(value.getAccessTime());
            setAccessRole(value.getAccessRole());
            setAccessUri(value.getAccessUri());
            resetChangedOnNotNull();
        }
    }
}
