/*
 * This file is generated by jOOQ.
 */
package kr.co.ihab.speechear.persistence.jooq.tables.records;


import javax.annotation.processing.Generated;

import kr.co.ihab.speechear.persistence.jooq.tables.UserAssignment;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserAssignmentRecord extends UpdatableRecordImpl<UserAssignmentRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.user_assignment.id</code>.
     */
    public UserAssignmentRecord setId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.user_assignment.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.user_assignment.manager</code>.
     */
    public UserAssignmentRecord setManager(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.user_assignment.manager</code>.
     */
    public String getManager() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return UserAssignment.USER_ASSIGNMENT.ID;
    }

    @Override
    public Field<String> field2() {
        return UserAssignment.USER_ASSIGNMENT.MANAGER;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getManager();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getManager();
    }

    @Override
    public UserAssignmentRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public UserAssignmentRecord value2(String value) {
        setManager(value);
        return this;
    }

    @Override
    public UserAssignmentRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserAssignmentRecord
     */
    public UserAssignmentRecord() {
        super(UserAssignment.USER_ASSIGNMENT);
    }

    /**
     * Create a detached, initialised UserAssignmentRecord
     */
    public UserAssignmentRecord(String id, String manager) {
        super(UserAssignment.USER_ASSIGNMENT);

        setId(id);
        setManager(manager);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised UserAssignmentRecord
     */
    public UserAssignmentRecord(kr.co.ihab.speechear.persistence.jooq.tables.pojos.UserAssignment value) {
        super(UserAssignment.USER_ASSIGNMENT);

        if (value != null) {
            setId(value.getId());
            setManager(value.getManager());
            resetChangedOnNotNull();
        }
    }
}
