/*
 * This file is generated by jOOQ.
 */
package kr.co.ihab.speechear.persistence.jooq.tables.records;


import javax.annotation.processing.Generated;

import kr.co.ihab.speechear.persistence.jooq.tables.UserTrainingType;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserTrainingTypeRecord extends UpdatableRecordImpl<UserTrainingTypeRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.user_training_type.training_id</code>.
     */
    public UserTrainingTypeRecord setTrainingId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.user_training_type.training_id</code>.
     */
    public String getTrainingId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.user_training_type.training_name</code>.
     */
    public UserTrainingTypeRecord setTrainingName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.user_training_type.training_name</code>.
     */
    public String getTrainingName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return UserTrainingType.USER_TRAINING_TYPE.TRAINING_ID;
    }

    @Override
    public Field<String> field2() {
        return UserTrainingType.USER_TRAINING_TYPE.TRAINING_NAME;
    }

    @Override
    public String component1() {
        return getTrainingId();
    }

    @Override
    public String component2() {
        return getTrainingName();
    }

    @Override
    public String value1() {
        return getTrainingId();
    }

    @Override
    public String value2() {
        return getTrainingName();
    }

    @Override
    public UserTrainingTypeRecord value1(String value) {
        setTrainingId(value);
        return this;
    }

    @Override
    public UserTrainingTypeRecord value2(String value) {
        setTrainingName(value);
        return this;
    }

    @Override
    public UserTrainingTypeRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserTrainingTypeRecord
     */
    public UserTrainingTypeRecord() {
        super(UserTrainingType.USER_TRAINING_TYPE);
    }

    /**
     * Create a detached, initialised UserTrainingTypeRecord
     */
    public UserTrainingTypeRecord(String trainingId, String trainingName) {
        super(UserTrainingType.USER_TRAINING_TYPE);

        setTrainingId(trainingId);
        setTrainingName(trainingName);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised UserTrainingTypeRecord
     */
    public UserTrainingTypeRecord(kr.co.ihab.speechear.persistence.jooq.tables.pojos.UserTrainingType value) {
        super(UserTrainingType.USER_TRAINING_TYPE);

        if (value != null) {
            setTrainingId(value.getTrainingId());
            setTrainingName(value.getTrainingName());
            resetChangedOnNotNull();
        }
    }
}
