/*
 * This file is generated by jOOQ.
 */
package kr.co.ihab.speechear.persistence.jooq.tables.records;


import javax.annotation.processing.Generated;

import kr.co.ihab.speechear.persistence.jooq.tables.UserTrainingGroup;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserTrainingGroupRecord extends UpdatableRecordImpl<UserTrainingGroupRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.user_training_group.training_id</code>.
     */
    public UserTrainingGroupRecord setTrainingId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.user_training_group.training_id</code>.
     */
    public String getTrainingId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.user_training_group.training_category</code>.
     */
    public UserTrainingGroupRecord setTrainingCategory(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.user_training_group.training_category</code>.
     */
    public String getTrainingCategory() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.user_training_group.category_name</code>.
     */
    public UserTrainingGroupRecord setCategoryName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.user_training_group.category_name</code>.
     */
    public String getCategoryName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<String, String, String> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return UserTrainingGroup.USER_TRAINING_GROUP.TRAINING_ID;
    }

    @Override
    public Field<String> field2() {
        return UserTrainingGroup.USER_TRAINING_GROUP.TRAINING_CATEGORY;
    }

    @Override
    public Field<String> field3() {
        return UserTrainingGroup.USER_TRAINING_GROUP.CATEGORY_NAME;
    }

    @Override
    public String component1() {
        return getTrainingId();
    }

    @Override
    public String component2() {
        return getTrainingCategory();
    }

    @Override
    public String component3() {
        return getCategoryName();
    }

    @Override
    public String value1() {
        return getTrainingId();
    }

    @Override
    public String value2() {
        return getTrainingCategory();
    }

    @Override
    public String value3() {
        return getCategoryName();
    }

    @Override
    public UserTrainingGroupRecord value1(String value) {
        setTrainingId(value);
        return this;
    }

    @Override
    public UserTrainingGroupRecord value2(String value) {
        setTrainingCategory(value);
        return this;
    }

    @Override
    public UserTrainingGroupRecord value3(String value) {
        setCategoryName(value);
        return this;
    }

    @Override
    public UserTrainingGroupRecord values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserTrainingGroupRecord
     */
    public UserTrainingGroupRecord() {
        super(UserTrainingGroup.USER_TRAINING_GROUP);
    }

    /**
     * Create a detached, initialised UserTrainingGroupRecord
     */
    public UserTrainingGroupRecord(String trainingId, String trainingCategory, String categoryName) {
        super(UserTrainingGroup.USER_TRAINING_GROUP);

        setTrainingId(trainingId);
        setTrainingCategory(trainingCategory);
        setCategoryName(categoryName);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised UserTrainingGroupRecord
     */
    public UserTrainingGroupRecord(kr.co.ihab.speechear.persistence.jooq.tables.pojos.UserTrainingGroup value) {
        super(UserTrainingGroup.USER_TRAINING_GROUP);

        if (value != null) {
            setTrainingId(value.getTrainingId());
            setTrainingCategory(value.getTrainingCategory());
            setCategoryName(value.getCategoryName());
            resetChangedOnNotNull();
        }
    }
}
