/*
 * This file is generated by jOOQ.
 */
package kr.co.ihab.speechear.persistence.jooq.tables;


import java.util.function.Function;

import javax.annotation.processing.Generated;

import kr.co.ihab.speechear.persistence.jooq.Public;
import kr.co.ihab.speechear.persistence.jooq.tables.records.Function5_1Record;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function14;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row14;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Function5_1 extends TableImpl<Function5_1Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.function5_1</code>
     */
    public static final Function5_1 FUNCTION5_1 = new Function5_1();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Function5_1Record> getRecordType() {
        return Function5_1Record.class;
    }

    /**
     * The column <code>public.function5_1.index</code>.
     */
    public final TableField<Function5_1Record, Integer> INDEX = createField(DSL.name("index"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.function5_1.col</code>.
     */
    public final TableField<Function5_1Record, Integer> COL = createField(DSL.name("col"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.function5_1.row</code>.
     */
    public final TableField<Function5_1Record, Integer> ROW = createField(DSL.name("row"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.function5_1.cnt</code>.
     */
    public final TableField<Function5_1Record, Integer> CNT = createField(DSL.name("cnt"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.function5_1.nullpoint</code>.
     */
    public final TableField<Function5_1Record, String> NULLPOINT = createField(DSL.name("nullpoint"), SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>public.function5_1.a</code>.
     */
    public final TableField<Function5_1Record, String> A = createField(DSL.name("a"), SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>public.function5_1.b</code>.
     */
    public final TableField<Function5_1Record, String> B = createField(DSL.name("b"), SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>public.function5_1.c</code>.
     */
    public final TableField<Function5_1Record, String> C = createField(DSL.name("c"), SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>public.function5_1.d</code>.
     */
    public final TableField<Function5_1Record, String> D = createField(DSL.name("d"), SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>public.function5_1.e</code>.
     */
    public final TableField<Function5_1Record, String> E = createField(DSL.name("e"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>public.function5_1.vertical</code>.
     */
    public final TableField<Function5_1Record, String> VERTICAL = createField(DSL.name("vertical"), SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>public.function5_1.horizontal</code>.
     */
    public final TableField<Function5_1Record, String> HORIZONTAL = createField(DSL.name("horizontal"), SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>public.function5_1.existpoint</code>.
     */
    public final TableField<Function5_1Record, String> EXISTPOINT = createField(DSL.name("existpoint"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.function5_1.context</code>.
     */
    public final TableField<Function5_1Record, String> CONTEXT = createField(DSL.name("context"), SQLDataType.VARCHAR(65).nullable(false), this, "");

    private Function5_1(Name alias, Table<Function5_1Record> aliased) {
        this(alias, aliased, null);
    }

    private Function5_1(Name alias, Table<Function5_1Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.function5_1</code> table reference
     */
    public Function5_1(String alias) {
        this(DSL.name(alias), FUNCTION5_1);
    }

    /**
     * Create an aliased <code>public.function5_1</code> table reference
     */
    public Function5_1(Name alias) {
        this(alias, FUNCTION5_1);
    }

    /**
     * Create a <code>public.function5_1</code> table reference
     */
    public Function5_1() {
        this(DSL.name("function5_1"), null);
    }

    public <O extends Record> Function5_1(Table<O> child, ForeignKey<O, Function5_1Record> key) {
        super(child, key, FUNCTION5_1);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Function5_1 as(String alias) {
        return new Function5_1(DSL.name(alias), this);
    }

    @Override
    public Function5_1 as(Name alias) {
        return new Function5_1(alias, this);
    }

    @Override
    public Function5_1 as(Table<?> alias) {
        return new Function5_1(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Function5_1 rename(String name) {
        return new Function5_1(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Function5_1 rename(Name name) {
        return new Function5_1(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Function5_1 rename(Table<?> name) {
        return new Function5_1(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row14 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row14<Integer, Integer, Integer, Integer, String, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function14<? super Integer, ? super Integer, ? super Integer, ? super Integer, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function14<? super Integer, ? super Integer, ? super Integer, ? super Integer, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
