/*
 * This file is generated by jOOQ.
 */
package kr.co.ihab.speechear.persistence.jooq.tables;


import java.util.function.Function;

import javax.annotation.processing.Generated;

import kr.co.ihab.speechear.persistence.jooq.Public;
import kr.co.ihab.speechear.persistence.jooq.tables.records.Function2Record;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function5;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Function2 extends TableImpl<Function2Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.function2</code>
     */
    public static final Function2 FUNCTION2 = new Function2();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Function2Record> getRecordType() {
        return Function2Record.class;
    }

    /**
     * The column <code>public.function2.speechcode</code>.
     */
    public final TableField<Function2Record, String> SPEECHCODE = createField(DSL.name("speechcode"), SQLDataType.VARCHAR(5).nullable(false), this, "");

    /**
     * The column <code>public.function2.speechcontext</code>.
     */
    public final TableField<Function2Record, String> SPEECHCONTEXT = createField(DSL.name("speechcontext"), SQLDataType.VARCHAR(210).nullable(false), this, "");

    /**
     * The column <code>public.function2.questioncode</code>.
     */
    public final TableField<Function2Record, String> QUESTIONCODE = createField(DSL.name("questioncode"), SQLDataType.VARCHAR(5).nullable(false), this, "");

    /**
     * The column <code>public.function2.questioncontext</code>.
     */
    public final TableField<Function2Record, String> QUESTIONCONTEXT = createField(DSL.name("questioncontext"), SQLDataType.VARCHAR(150).nullable(false), this, "");

    /**
     * The column <code>public.function2.answer</code>.
     */
    public final TableField<Function2Record, String> ANSWER = createField(DSL.name("answer"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    private Function2(Name alias, Table<Function2Record> aliased) {
        this(alias, aliased, null);
    }

    private Function2(Name alias, Table<Function2Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.function2</code> table reference
     */
    public Function2(String alias) {
        this(DSL.name(alias), FUNCTION2);
    }

    /**
     * Create an aliased <code>public.function2</code> table reference
     */
    public Function2(Name alias) {
        this(alias, FUNCTION2);
    }

    /**
     * Create a <code>public.function2</code> table reference
     */
    public Function2() {
        this(DSL.name("function2"), null);
    }

    public <O extends Record> Function2(Table<O> child, ForeignKey<O, Function2Record> key) {
        super(child, key, FUNCTION2);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Function2 as(String alias) {
        return new Function2(DSL.name(alias), this);
    }

    @Override
    public Function2 as(Name alias) {
        return new Function2(alias, this);
    }

    @Override
    public Function2 as(Table<?> alias) {
        return new Function2(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Function2 rename(String name) {
        return new Function2(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Function2 rename(Name name) {
        return new Function2(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Function2 rename(Table<?> name) {
        return new Function2(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<String, String, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function5<? super String, ? super String, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function5<? super String, ? super String, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
