/*
 * This file is generated by jOOQ.
 */
package kr.co.ihab.speechear.persistence.jooq.tables;


import java.util.function.Function;

import javax.annotation.processing.Generated;

import kr.co.ihab.speechear.persistence.jooq.Public;
import kr.co.ihab.speechear.persistence.jooq.tables.records.Function1Record;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Function1 extends TableImpl<Function1Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.function1</code>
     */
    public static final Function1 FUNCTION1 = new Function1();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Function1Record> getRecordType() {
        return Function1Record.class;
    }

    /**
     * The column <code>public.function1.index</code>.
     */
    public final TableField<Function1Record, String> INDEX = createField(DSL.name("index"), SQLDataType.VARCHAR(5).nullable(false), this, "");

    /**
     * The column <code>public.function1.filename</code>.
     */
    public final TableField<Function1Record, String> FILENAME = createField(DSL.name("filename"), SQLDataType.VARCHAR(7).nullable(false), this, "");

    /**
     * The column <code>public.function1.context</code>.
     */
    public final TableField<Function1Record, String> CONTEXT = createField(DSL.name("context"), SQLDataType.VARCHAR(125).nullable(false), this, "");

    private Function1(Name alias, Table<Function1Record> aliased) {
        this(alias, aliased, null);
    }

    private Function1(Name alias, Table<Function1Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.function1</code> table reference
     */
    public Function1(String alias) {
        this(DSL.name(alias), FUNCTION1);
    }

    /**
     * Create an aliased <code>public.function1</code> table reference
     */
    public Function1(Name alias) {
        this(alias, FUNCTION1);
    }

    /**
     * Create a <code>public.function1</code> table reference
     */
    public Function1() {
        this(DSL.name("function1"), null);
    }

    public <O extends Record> Function1(Table<O> child, ForeignKey<O, Function1Record> key) {
        super(child, key, FUNCTION1);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Function1 as(String alias) {
        return new Function1(DSL.name(alias), this);
    }

    @Override
    public Function1 as(Name alias) {
        return new Function1(alias, this);
    }

    @Override
    public Function1 as(Table<?> alias) {
        return new Function1(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Function1 rename(String name) {
        return new Function1(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Function1 rename(Name name) {
        return new Function1(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Function1 rename(Table<?> name) {
        return new Function1(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
