/*
 * This file is generated by jOOQ.
 */
package kr.co.ihab.speechear.persistence.jooq.tables;


import java.util.function.Function;

import javax.annotation.processing.Generated;

import kr.co.ihab.speechear.persistence.jooq.Public;
import kr.co.ihab.speechear.persistence.jooq.tables.records.Function5_2Record;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Function5_2 extends TableImpl<Function5_2Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.function5_2</code>
     */
    public static final Function5_2 FUNCTION5_2 = new Function5_2();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Function5_2Record> getRecordType() {
        return Function5_2Record.class;
    }

    /**
     * The column <code>public.function5_2.filename</code>.
     */
    public final TableField<Function5_2Record, String> FILENAME = createField(DSL.name("filename"), SQLDataType.VARCHAR(15).nullable(false), this, "");

    /**
     * The column <code>public.function5_2.context</code>.
     */
    public final TableField<Function5_2Record, String> CONTEXT = createField(DSL.name("context"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    private Function5_2(Name alias, Table<Function5_2Record> aliased) {
        this(alias, aliased, null);
    }

    private Function5_2(Name alias, Table<Function5_2Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.function5_2</code> table reference
     */
    public Function5_2(String alias) {
        this(DSL.name(alias), FUNCTION5_2);
    }

    /**
     * Create an aliased <code>public.function5_2</code> table reference
     */
    public Function5_2(Name alias) {
        this(alias, FUNCTION5_2);
    }

    /**
     * Create a <code>public.function5_2</code> table reference
     */
    public Function5_2() {
        this(DSL.name("function5_2"), null);
    }

    public <O extends Record> Function5_2(Table<O> child, ForeignKey<O, Function5_2Record> key) {
        super(child, key, FUNCTION5_2);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Function5_2 as(String alias) {
        return new Function5_2(DSL.name(alias), this);
    }

    @Override
    public Function5_2 as(Name alias) {
        return new Function5_2(alias, this);
    }

    @Override
    public Function5_2 as(Table<?> alias) {
        return new Function5_2(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Function5_2 rename(String name) {
        return new Function5_2(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Function5_2 rename(Name name) {
        return new Function5_2(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Function5_2 rename(Table<?> name) {
        return new Function5_2(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
