/*
 * This file is generated by jOOQ.
 */
package kr.co.ihab.speechear.persistence.jooq.tables;


import java.util.function.Function;

import javax.annotation.processing.Generated;

import kr.co.ihab.speechear.persistence.jooq.Keys;
import kr.co.ihab.speechear.persistence.jooq.Public;
import kr.co.ihab.speechear.persistence.jooq.tables.records.RoleInfoRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoleInfo extends TableImpl<RoleInfoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.role_info</code>
     */
    public static final RoleInfo ROLE_INFO = new RoleInfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RoleInfoRecord> getRecordType() {
        return RoleInfoRecord.class;
    }

    /**
     * The column <code>public.role_info.id</code>.
     */
    public final TableField<RoleInfoRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.role_info.name</code>.
     */
    public final TableField<RoleInfoRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255), this, "");

    private RoleInfo(Name alias, Table<RoleInfoRecord> aliased) {
        this(alias, aliased, null);
    }

    private RoleInfo(Name alias, Table<RoleInfoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.role_info</code> table reference
     */
    public RoleInfo(String alias) {
        this(DSL.name(alias), ROLE_INFO);
    }

    /**
     * Create an aliased <code>public.role_info</code> table reference
     */
    public RoleInfo(Name alias) {
        this(alias, ROLE_INFO);
    }

    /**
     * Create a <code>public.role_info</code> table reference
     */
    public RoleInfo() {
        this(DSL.name("role_info"), null);
    }

    public <O extends Record> RoleInfo(Table<O> child, ForeignKey<O, RoleInfoRecord> key) {
        super(child, key, ROLE_INFO);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<RoleInfoRecord> getPrimaryKey() {
        return Keys.ROLE_INFO_PK;
    }

    @Override
    public RoleInfo as(String alias) {
        return new RoleInfo(DSL.name(alias), this);
    }

    @Override
    public RoleInfo as(Name alias) {
        return new RoleInfo(alias, this);
    }

    @Override
    public RoleInfo as(Table<?> alias) {
        return new RoleInfo(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RoleInfo rename(String name) {
        return new RoleInfo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RoleInfo rename(Name name) {
        return new RoleInfo(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RoleInfo rename(Table<?> name) {
        return new RoleInfo(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Long, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Long, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
