/*
 * This file is generated by jOOQ.
 */
package kr.co.ihab.speechear.persistence.jooq.tables;


import java.util.function.Function;

import javax.annotation.processing.Generated;

import kr.co.ihab.speechear.persistence.jooq.Keys;
import kr.co.ihab.speechear.persistence.jooq.Public;
import kr.co.ihab.speechear.persistence.jooq.tables.records.UserSettingRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserSetting extends TableImpl<UserSettingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.user_setting</code>
     */
    public static final UserSetting USER_SETTING = new UserSetting();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserSettingRecord> getRecordType() {
        return UserSettingRecord.class;
    }

    /**
     * The column <code>public.user_setting.user_id</code>.
     */
    public final TableField<UserSettingRecord, String> USER_ID = createField(DSL.name("user_id"), SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>public.user_setting.noise_type</code>.
     */
    public final TableField<UserSettingRecord, String> NOISE_TYPE = createField(DSL.name("noise_type"), SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>public.user_setting.play_speed</code>.
     */
    public final TableField<UserSettingRecord, String> PLAY_SPEED = createField(DSL.name("play_speed"), SQLDataType.VARCHAR(12).nullable(false), this, "");

    private UserSetting(Name alias, Table<UserSettingRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserSetting(Name alias, Table<UserSettingRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.user_setting</code> table reference
     */
    public UserSetting(String alias) {
        this(DSL.name(alias), USER_SETTING);
    }

    /**
     * Create an aliased <code>public.user_setting</code> table reference
     */
    public UserSetting(Name alias) {
        this(alias, USER_SETTING);
    }

    /**
     * Create a <code>public.user_setting</code> table reference
     */
    public UserSetting() {
        this(DSL.name("user_setting"), null);
    }

    public <O extends Record> UserSetting(Table<O> child, ForeignKey<O, UserSettingRecord> key) {
        super(child, key, USER_SETTING);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<UserSettingRecord> getPrimaryKey() {
        return Keys.USER_SETTING_PK;
    }

    @Override
    public UserSetting as(String alias) {
        return new UserSetting(DSL.name(alias), this);
    }

    @Override
    public UserSetting as(Name alias) {
        return new UserSetting(alias, this);
    }

    @Override
    public UserSetting as(Table<?> alias) {
        return new UserSetting(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserSetting rename(String name) {
        return new UserSetting(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserSetting rename(Name name) {
        return new UserSetting(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserSetting rename(Table<?> name) {
        return new UserSetting(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
