/*
 * This file is generated by jOOQ.
 */
package kr.co.ihab.speechear.persistence.jooq.tables;


import java.util.function.Function;

import javax.annotation.processing.Generated;

import kr.co.ihab.speechear.persistence.jooq.Keys;
import kr.co.ihab.speechear.persistence.jooq.Public;
import kr.co.ihab.speechear.persistence.jooq.tables.records.UserTrainingScoreRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function5;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserTrainingScore extends TableImpl<UserTrainingScoreRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.user_training_score</code>
     */
    public static final UserTrainingScore USER_TRAINING_SCORE = new UserTrainingScore();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserTrainingScoreRecord> getRecordType() {
        return UserTrainingScoreRecord.class;
    }

    /**
     * The column <code>public.user_training_score.user_id</code>.
     */
    public final TableField<UserTrainingScoreRecord, String> USER_ID = createField(DSL.name("user_id"), SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>public.user_training_score.training_id</code>.
     */
    public final TableField<UserTrainingScoreRecord, String> TRAINING_ID = createField(DSL.name("training_id"), SQLDataType.VARCHAR(2).nullable(false), this, "");

    /**
     * The column <code>public.user_training_score.training_category</code>.
     */
    public final TableField<UserTrainingScoreRecord, String> TRAINING_CATEGORY = createField(DSL.name("training_category"), SQLDataType.VARCHAR(1).nullable(false), this, "");

    /**
     * The column <code>public.user_training_score.training_chapter</code>.
     */
    public final TableField<UserTrainingScoreRecord, Integer> TRAINING_CHAPTER = createField(DSL.name("training_chapter"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.user_training_score.user_score</code>.
     */
    public final TableField<UserTrainingScoreRecord, Integer> USER_SCORE = createField(DSL.name("user_score"), SQLDataType.INTEGER.nullable(false), this, "");

    private UserTrainingScore(Name alias, Table<UserTrainingScoreRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserTrainingScore(Name alias, Table<UserTrainingScoreRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.user_training_score</code> table reference
     */
    public UserTrainingScore(String alias) {
        this(DSL.name(alias), USER_TRAINING_SCORE);
    }

    /**
     * Create an aliased <code>public.user_training_score</code> table reference
     */
    public UserTrainingScore(Name alias) {
        this(alias, USER_TRAINING_SCORE);
    }

    /**
     * Create a <code>public.user_training_score</code> table reference
     */
    public UserTrainingScore() {
        this(DSL.name("user_training_score"), null);
    }

    public <O extends Record> UserTrainingScore(Table<O> child, ForeignKey<O, UserTrainingScoreRecord> key) {
        super(child, key, USER_TRAINING_SCORE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<UserTrainingScoreRecord> getPrimaryKey() {
        return Keys.USER_TRAINING_SCORE_PK;
    }

    @Override
    public UserTrainingScore as(String alias) {
        return new UserTrainingScore(DSL.name(alias), this);
    }

    @Override
    public UserTrainingScore as(Name alias) {
        return new UserTrainingScore(alias, this);
    }

    @Override
    public UserTrainingScore as(Table<?> alias) {
        return new UserTrainingScore(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserTrainingScore rename(String name) {
        return new UserTrainingScore(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserTrainingScore rename(Name name) {
        return new UserTrainingScore(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserTrainingScore rename(Table<?> name) {
        return new UserTrainingScore(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<String, String, String, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function5<? super String, ? super String, ? super String, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function5<? super String, ? super String, ? super String, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
