/*
 * This file is generated by jOOQ.
 */
package kr.co.ihab.speechear.persistence.jooq.tables;


import java.util.function.Function;

import javax.annotation.processing.Generated;

import kr.co.ihab.speechear.persistence.jooq.Keys;
import kr.co.ihab.speechear.persistence.jooq.Public;
import kr.co.ihab.speechear.persistence.jooq.tables.records.UserTrainingProgressRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function5;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserTrainingProgress extends TableImpl<UserTrainingProgressRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.user_training_progress</code>
     */
    public static final UserTrainingProgress USER_TRAINING_PROGRESS = new UserTrainingProgress();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserTrainingProgressRecord> getRecordType() {
        return UserTrainingProgressRecord.class;
    }

    /**
     * The column <code>public.user_training_progress.user_id</code>.
     */
    public final TableField<UserTrainingProgressRecord, String> USER_ID = createField(DSL.name("user_id"), SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>public.user_training_progress.training_id</code>.
     */
    public final TableField<UserTrainingProgressRecord, String> TRAINING_ID = createField(DSL.name("training_id"), SQLDataType.VARCHAR(2).nullable(false), this, "");

    /**
     * The column <code>public.user_training_progress.training_category</code>.
     */
    public final TableField<UserTrainingProgressRecord, String> TRAINING_CATEGORY = createField(DSL.name("training_category"), SQLDataType.VARCHAR(1).nullable(false), this, "");

    /**
     * The column <code>public.user_training_progress.training_chapter</code>.
     */
    public final TableField<UserTrainingProgressRecord, Integer> TRAINING_CHAPTER = createField(DSL.name("training_chapter"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.user_training_progress.user_act</code>.
     */
    public final TableField<UserTrainingProgressRecord, Integer> USER_ACT = createField(DSL.name("user_act"), SQLDataType.INTEGER.nullable(false), this, "");

    private UserTrainingProgress(Name alias, Table<UserTrainingProgressRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserTrainingProgress(Name alias, Table<UserTrainingProgressRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.user_training_progress</code> table
     * reference
     */
    public UserTrainingProgress(String alias) {
        this(DSL.name(alias), USER_TRAINING_PROGRESS);
    }

    /**
     * Create an aliased <code>public.user_training_progress</code> table
     * reference
     */
    public UserTrainingProgress(Name alias) {
        this(alias, USER_TRAINING_PROGRESS);
    }

    /**
     * Create a <code>public.user_training_progress</code> table reference
     */
    public UserTrainingProgress() {
        this(DSL.name("user_training_progress"), null);
    }

    public <O extends Record> UserTrainingProgress(Table<O> child, ForeignKey<O, UserTrainingProgressRecord> key) {
        super(child, key, USER_TRAINING_PROGRESS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<UserTrainingProgressRecord> getPrimaryKey() {
        return Keys.USER_TRAINING_PROGRESS_PK;
    }

    @Override
    public UserTrainingProgress as(String alias) {
        return new UserTrainingProgress(DSL.name(alias), this);
    }

    @Override
    public UserTrainingProgress as(Name alias) {
        return new UserTrainingProgress(alias, this);
    }

    @Override
    public UserTrainingProgress as(Table<?> alias) {
        return new UserTrainingProgress(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserTrainingProgress rename(String name) {
        return new UserTrainingProgress(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserTrainingProgress rename(Name name) {
        return new UserTrainingProgress(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserTrainingProgress rename(Table<?> name) {
        return new UserTrainingProgress(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<String, String, String, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function5<? super String, ? super String, ? super String, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function5<? super String, ? super String, ? super String, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
