/*
 * This file is generated by jOOQ.
 */
package kr.co.ihab.speechear.persistence.jooq.tables;


import java.util.function.Function;

import javax.annotation.processing.Generated;

import kr.co.ihab.speechear.persistence.jooq.Keys;
import kr.co.ihab.speechear.persistence.jooq.Public;
import kr.co.ihab.speechear.persistence.jooq.tables.records.UserTrainingTypeRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserTrainingType extends TableImpl<UserTrainingTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.user_training_type</code>
     */
    public static final UserTrainingType USER_TRAINING_TYPE = new UserTrainingType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserTrainingTypeRecord> getRecordType() {
        return UserTrainingTypeRecord.class;
    }

    /**
     * The column <code>public.user_training_type.training_id</code>.
     */
    public final TableField<UserTrainingTypeRecord, String> TRAINING_ID = createField(DSL.name("training_id"), SQLDataType.VARCHAR(2).nullable(false), this, "");

    /**
     * The column <code>public.user_training_type.training_name</code>.
     */
    public final TableField<UserTrainingTypeRecord, String> TRAINING_NAME = createField(DSL.name("training_name"), SQLDataType.VARCHAR(10).nullable(false), this, "");

    private UserTrainingType(Name alias, Table<UserTrainingTypeRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserTrainingType(Name alias, Table<UserTrainingTypeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.user_training_type</code> table reference
     */
    public UserTrainingType(String alias) {
        this(DSL.name(alias), USER_TRAINING_TYPE);
    }

    /**
     * Create an aliased <code>public.user_training_type</code> table reference
     */
    public UserTrainingType(Name alias) {
        this(alias, USER_TRAINING_TYPE);
    }

    /**
     * Create a <code>public.user_training_type</code> table reference
     */
    public UserTrainingType() {
        this(DSL.name("user_training_type"), null);
    }

    public <O extends Record> UserTrainingType(Table<O> child, ForeignKey<O, UserTrainingTypeRecord> key) {
        super(child, key, USER_TRAINING_TYPE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<UserTrainingTypeRecord> getPrimaryKey() {
        return Keys.USER_TRAINING_TYPE_PK;
    }

    @Override
    public UserTrainingType as(String alias) {
        return new UserTrainingType(DSL.name(alias), this);
    }

    @Override
    public UserTrainingType as(Name alias) {
        return new UserTrainingType(alias, this);
    }

    @Override
    public UserTrainingType as(Table<?> alias) {
        return new UserTrainingType(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserTrainingType rename(String name) {
        return new UserTrainingType(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserTrainingType rename(Name name) {
        return new UserTrainingType(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserTrainingType rename(Table<?> name) {
        return new UserTrainingType(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
