/*
 * This file is generated by jOOQ.
 */
package kr.co.ihab.speechear.persistence.jooq;


import javax.annotation.processing.Generated;

import kr.co.ihab.speechear.persistence.jooq.tables.FileInfo;
import kr.co.ihab.speechear.persistence.jooq.tables.Function1;
import kr.co.ihab.speechear.persistence.jooq.tables.Function2;
import kr.co.ihab.speechear.persistence.jooq.tables.Function3_1;
import kr.co.ihab.speechear.persistence.jooq.tables.Function3_2;
import kr.co.ihab.speechear.persistence.jooq.tables.Function4;
import kr.co.ihab.speechear.persistence.jooq.tables.Function5_1;
import kr.co.ihab.speechear.persistence.jooq.tables.Function5_2;
import kr.co.ihab.speechear.persistence.jooq.tables.RoleInfo;
import kr.co.ihab.speechear.persistence.jooq.tables.UserActivity;
import kr.co.ihab.speechear.persistence.jooq.tables.UserAssignment;
import kr.co.ihab.speechear.persistence.jooq.tables.UserInfo;
import kr.co.ihab.speechear.persistence.jooq.tables.UserLog;
import kr.co.ihab.speechear.persistence.jooq.tables.UserRoles;
import kr.co.ihab.speechear.persistence.jooq.tables.UserSetting;
import kr.co.ihab.speechear.persistence.jooq.tables.UserTrainingChapter;
import kr.co.ihab.speechear.persistence.jooq.tables.UserTrainingGroup;
import kr.co.ihab.speechear.persistence.jooq.tables.UserTrainingProgress;
import kr.co.ihab.speechear.persistence.jooq.tables.UserTrainingScore;
import kr.co.ihab.speechear.persistence.jooq.tables.UserTrainingType;


/**
 * Convenience access to all tables in public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.file_info</code>.
     */
    public static final FileInfo FILE_INFO = FileInfo.FILE_INFO;

    /**
     * The table <code>public.function1</code>.
     */
    public static final Function1 FUNCTION1 = Function1.FUNCTION1;

    /**
     * The table <code>public.function2</code>.
     */
    public static final Function2 FUNCTION2 = Function2.FUNCTION2;

    /**
     * The table <code>public.function3_1</code>.
     */
    public static final Function3_1 FUNCTION3_1 = Function3_1.FUNCTION3_1;

    /**
     * The table <code>public.function3_2</code>.
     */
    public static final Function3_2 FUNCTION3_2 = Function3_2.FUNCTION3_2;

    /**
     * The table <code>public.function4</code>.
     */
    public static final Function4 FUNCTION4 = Function4.FUNCTION4;

    /**
     * The table <code>public.function5_1</code>.
     */
    public static final Function5_1 FUNCTION5_1 = Function5_1.FUNCTION5_1;

    /**
     * The table <code>public.function5_2</code>.
     */
    public static final Function5_2 FUNCTION5_2 = Function5_2.FUNCTION5_2;

    /**
     * The table <code>public.role_info</code>.
     */
    public static final RoleInfo ROLE_INFO = RoleInfo.ROLE_INFO;

    /**
     * The table <code>public.user_activity</code>.
     */
    public static final UserActivity USER_ACTIVITY = UserActivity.USER_ACTIVITY;

    /**
     * The table <code>public.user_assignment</code>.
     */
    public static final UserAssignment USER_ASSIGNMENT = UserAssignment.USER_ASSIGNMENT;

    /**
     * The table <code>public.user_info</code>.
     */
    public static final UserInfo USER_INFO = UserInfo.USER_INFO;

    /**
     * The table <code>public.user_log</code>.
     */
    public static final UserLog USER_LOG = UserLog.USER_LOG;

    /**
     * The table <code>public.user_roles</code>.
     */
    public static final UserRoles USER_ROLES = UserRoles.USER_ROLES;

    /**
     * The table <code>public.user_setting</code>.
     */
    public static final UserSetting USER_SETTING = UserSetting.USER_SETTING;

    /**
     * The table <code>public.user_training_chapter</code>.
     */
    public static final UserTrainingChapter USER_TRAINING_CHAPTER = UserTrainingChapter.USER_TRAINING_CHAPTER;

    /**
     * The table <code>public.user_training_group</code>.
     */
    public static final UserTrainingGroup USER_TRAINING_GROUP = UserTrainingGroup.USER_TRAINING_GROUP;

    /**
     * The table <code>public.user_training_progress</code>.
     */
    public static final UserTrainingProgress USER_TRAINING_PROGRESS = UserTrainingProgress.USER_TRAINING_PROGRESS;

    /**
     * The table <code>public.user_training_score</code>.
     */
    public static final UserTrainingScore USER_TRAINING_SCORE = UserTrainingScore.USER_TRAINING_SCORE;

    /**
     * The table <code>public.user_training_type</code>.
     */
    public static final UserTrainingType USER_TRAINING_TYPE = UserTrainingType.USER_TRAINING_TYPE;
}
